#!/bin/dash

# Autostart Apps
xset +fp ~/.fonts/misc/
xset b off
xset r rate 250 25
/usr/lib/policykit-1-gnome/polkit-gnome-authentication-agent-1 &
picom -b

hsetroot -fill ~/.config/wallpaper/wallpaper.jpg
xsettingsd &
dunst -geometry "300x60-28+56" &

trayer \
--align right --widthtype request --heighttype pixel --height 28 \
--transparent true --alpha 255 &

polybar
